---
all:
  hosts:
    el-instance:
      ansible_host: 51.250.12.68
    kb-instance:
      ansible_host: 51.250.14.158
    app-instance:
      ansible_host: 51.250.6.241
  vars:
    ansible_connection: ssh
    ansible_user: maxn
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    kb-instance:
filebeat:
  hosts:
    app-instance: